# Generated by Django 3.1.4 on 2020-12-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodid', models.AutoField(primary_key=True, serialize=False)),
                ('foodname', models.CharField(max_length=30)),
                ('foodcat', models.CharField(max_length=30)),
                ('foodtype', models.CharField(max_length=15)),
                ('foodprice', models.FloatField(max_length=15)),
                ('foodquantity', models.IntegerField(default=0)),
                ('foodimg', models.ImageField(default='', upload_to='')),
            ],
            options={
                'db_table': 'Food',
            },
        ),
    ]
