# Generated by Django 3.1.4 on 2020-12-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20201218_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='custcontact',
            field=models.CharField(max_length=10),
        ),
    ]
