# Generated by Django 3.1.4 on 2020-12-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20201218_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminname', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('adminpass', models.CharField(max_length=10)),
            ],
        ),
    ]
