# Generated by Django 3.1.4 on 2020-12-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.AutoField(primary_key=True, serialize=False)),
                ('custemail', models.CharField(max_length=30)),
                ('foodid', models.IntegerField()),
                ('foodquantity', models.IntegerField()),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.AlterModelTable(
            name='admin',
            table='Admin',
        ),
    ]
