# Generated by Django 3.1.4 on 2020-12-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20201223_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='foodid',
            new_name='fdid',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='foodquantity',
            new_name='foodqnty',
        ),
    ]
