# Generated by Django 3.1.4 on 2020-12-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20201224_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='fdid',
            new_name='fid',
        ),
    ]
