# Generated by Django 3.1.4 on 2020-12-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20201224_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='foodqnty',
            field=models.IntegerField(default=1),
        ),
    ]
