# Generated by Django 3.1.4 on 2021-01-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_ordersummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersummary',
            old_name='orderid',
            new_name='odrid',
        ),
    ]
